/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import comparadorpc.LogicMaster;

/**
 *
 * @author andre
 */
public class Dashboard extends javax.swing.JFrame {
    
    public static LogicMaster puppetMasterMagenta;
    public static LogicMaster puppLogicMasterNeon;

    /**
     * Creates new form Dashboard
     */
    public Dashboard(LogicMaster dellController, LogicMaster msiController) {
        initComponents();
        this.puppetMasterMagenta = dellController;
        this.puppetMasterMagenta = msiController;
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        gananciasBruto_DELL = new javax.swing.JTextField();
        utilidadTotal_DELL = new javax.swing.JTextField();
        costosOper_DELL = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        utilidadTotal_MSI = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        costosOper_MSI = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        gananciasBruto_MSI = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Ganancias en Bruto");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 80, 230, 30);

        gananciasBruto_DELL.setEditable(false);
        gananciasBruto_DELL.setBackground(new java.awt.Color(255, 255, 255));
        gananciasBruto_DELL.setForeground(new java.awt.Color(51, 51, 51));
        gananciasBruto_DELL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gananciasBruto_DELLActionPerformed(evt);
            }
        });
        jPanel1.add(gananciasBruto_DELL);
        gananciasBruto_DELL.setBounds(40, 120, 160, 30);

        utilidadTotal_DELL.setEditable(false);
        utilidadTotal_DELL.setBackground(new java.awt.Color(255, 255, 255));
        utilidadTotal_DELL.setForeground(new java.awt.Color(51, 51, 51));
        utilidadTotal_DELL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utilidadTotal_DELLActionPerformed(evt);
            }
        });
        jPanel1.add(utilidadTotal_DELL);
        utilidadTotal_DELL.setBounds(40, 310, 160, 30);

        costosOper_DELL.setEditable(false);
        costosOper_DELL.setBackground(new java.awt.Color(255, 255, 255));
        costosOper_DELL.setForeground(new java.awt.Color(51, 51, 51));
        costosOper_DELL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costosOper_DELLActionPerformed(evt);
            }
        });
        jPanel1.add(costosOper_DELL);
        costosOper_DELL.setBounds(40, 220, 160, 30);

        jLabel28.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("DASHBOARD");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(280, 10, 180, 30);

        jLabel14.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Costos Operativos");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(30, 170, 230, 30);

        jLabel15.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Utilidad total del estudio");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(30, 270, 250, 30);

        utilidadTotal_MSI.setEditable(false);
        utilidadTotal_MSI.setBackground(new java.awt.Color(255, 255, 255));
        utilidadTotal_MSI.setForeground(new java.awt.Color(51, 51, 51));
        utilidadTotal_MSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utilidadTotal_MSIActionPerformed(evt);
            }
        });
        jPanel1.add(utilidadTotal_MSI);
        utilidadTotal_MSI.setBounds(420, 310, 160, 30);

        jLabel16.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Utilidad total del estudio");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(410, 270, 250, 30);

        costosOper_MSI.setEditable(false);
        costosOper_MSI.setBackground(new java.awt.Color(255, 255, 255));
        costosOper_MSI.setForeground(new java.awt.Color(51, 51, 51));
        costosOper_MSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costosOper_MSIActionPerformed(evt);
            }
        });
        jPanel1.add(costosOper_MSI);
        costosOper_MSI.setBounds(420, 220, 160, 30);

        jLabel17.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Costos Operativos");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(410, 170, 230, 30);

        gananciasBruto_MSI.setEditable(false);
        gananciasBruto_MSI.setBackground(new java.awt.Color(255, 255, 255));
        gananciasBruto_MSI.setForeground(new java.awt.Color(51, 51, 51));
        gananciasBruto_MSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gananciasBruto_MSIActionPerformed(evt);
            }
        });
        jPanel1.add(gananciasBruto_MSI);
        gananciasBruto_MSI.setBounds(420, 120, 160, 30);

        jLabel18.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Ganancias en Bruto");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(410, 80, 230, 30);

        try {
            wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/dashboard_wallpp.png"))); // NOI18N
            jPanel1.add(wallpaper);
            wallpaper.setBounds(0, 0, 733, 370); 
        } catch (Exception e) {
            // TODO: handle exception
        }
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gananciasBruto_DELLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gananciasBruto_DELLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gananciasBruto_DELLActionPerformed

    private void utilidadTotal_DELLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utilidadTotal_DELLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utilidadTotal_DELLActionPerformed

    private void costosOper_DELLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costosOper_DELLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costosOper_DELLActionPerformed

    private void utilidadTotal_MSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utilidadTotal_MSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utilidadTotal_MSIActionPerformed

    private void costosOper_MSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costosOper_MSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costosOper_MSIActionPerformed

    private void gananciasBruto_MSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gananciasBruto_MSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gananciasBruto_MSIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard(puppetMasterMagenta, puppLogicMasterNeon).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField costosOper_DELL;
    private javax.swing.JTextField costosOper_MSI;
    private javax.swing.JTextField gananciasBruto_DELL;
    private javax.swing.JTextField gananciasBruto_MSI;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField utilidadTotal_DELL;
    private javax.swing.JTextField utilidadTotal_MSI;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
