/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import comparadorpc.LogicMaster;

/**
 *
 * @author andre
 */
public class HomeScreen extends javax.swing.JFrame {

    public static LogicMaster puppetMasterMagenta;
    public static LogicMaster puppetMasterNeon;
    /**
     * Creates new form HomeScreen
     */
    public HomeScreen(LogicMaster dellController, LogicMaster msiController) {
        initComponents();
        this.puppetMasterMagenta = dellController;
        this.puppetMasterNeon = msiController;
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        openSimulationScreenButton = new javax.swing.JButton();
        uploadTxtButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        openSimulationScreenButton.setBackground(new java.awt.Color(204, 204, 204));
        openSimulationScreenButton.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        openSimulationScreenButton.setForeground(new java.awt.Color(0, 0, 0));
        openSimulationScreenButton.setText("Entrar al Simulador");
        openSimulationScreenButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        openSimulationScreenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openSimulationScreenButtonActionPerformed(evt);
            }
        });
        jPanel1.add(openSimulationScreenButton);
        openSimulationScreenButton.setBounds(380, 90, 206, 64);

        uploadTxtButton.setBackground(new java.awt.Color(204, 204, 204));
        uploadTxtButton.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        uploadTxtButton.setForeground(new java.awt.Color(0, 0, 0));
        uploadTxtButton.setText("Subir archivo .txt");
        uploadTxtButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        uploadTxtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadTxtButtonActionPerformed(evt);
            }
        });
        jPanel1.add(uploadTxtButton);
        uploadTxtButton.setBounds(370, 440, 206, 42);

        ExitButton.setBackground(new java.awt.Color(204, 204, 204));
        ExitButton.setForeground(new java.awt.Color(0, 0, 0));
        ExitButton.setText("Salir");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ExitButton);
        ExitButton.setBounds(20, 490, 92, 35);

        try {
            Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Modelos - Proyecto SSOO 1 - Main screen.png")));
            jPanel1.add(Wallpaper);
            Wallpaper.setBounds(0, 0, 960, 540);
        } catch (Exception e) {
            // TODO: handle exception
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void uploadTxtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadTxtButtonActionPerformed
        //this.puppetMaster.FileChooser();
    }//GEN-LAST:event_uploadTxtButtonActionPerformed

    private void openSimulationScreenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openSimulationScreenButtonActionPerformed
        SimulationScreen w2 = new SimulationScreen(puppetMasterMagenta, puppetMasterNeon);
        this.dispose();
    }//GEN-LAST:event_openSimulationScreenButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen(puppetMasterMagenta, puppetMasterNeon).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel Wallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton openSimulationScreenButton;
    private javax.swing.JButton uploadTxtButton;
    // End of variables declaration//GEN-END:variables
}
