/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import comparadorpc.LogicMaster;

/**
 *
 * @author andre
 */
public class SimulationScreen extends javax.swing.JFrame {

    public static LogicMaster puppetMasterMagenta;
    public static LogicMaster puppetMasterNeon;
    
    /**
     * Creates new form SimulationScreen
     */
    public SimulationScreen(LogicMaster dellController, LogicMaster msiController) {
        this.puppetMasterMagenta = dellController;
        this.puppetMasterNeon = msiController;
        initComponents();
        this.summonPiecesData();
        this.summonCompletePCData();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        placasBaseAlmacen_DELL = new javax.swing.JTextField();
        CPUalmacen_DELL = new javax.swing.JTextField();
        RAMalmacen_DELL = new javax.swing.JTextField();
        AlimentacionAlmacen_DELL = new javax.swing.JTextField();
        TGAlmacen_DELL = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PCwTG_DELL = new javax.swing.JTextField();
        PCEstandar_DELL = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ingresos_DELL = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        availibleWorkers_DELL = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        directorState_DELL = new javax.swing.JTextField();
        PMState_DELL = new javax.swing.JTextField();
        PMfaultCount_DELL = new javax.swing.JTextField();
        PMwageLoss_DELL = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        displayDashboard_Button = new javax.swing.JButton();
        PCwTG_MSI = new javax.swing.JTextField();
        ingresos_MSI = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        PCEstandar_MSI = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        TGalmacen_MSI = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        fuentesAlimAlmacen_MSI = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        CPUAlmacen_MSI = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        placasBaseAlmacen_MSI = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        availibleWorkers_MSI = new javax.swing.JTextField();
        PMwageLoss_MSI = new javax.swing.JTextField();
        PMFaultCount_MSI = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        PMState_MSI = new javax.swing.JTextField();
        directorState_MSI = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        RAMalmacen_MSI = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        back_Button = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        jSpinner7 = new javax.swing.JSpinner();
        jSpinner8 = new javax.swing.JSpinner();
        jSpinner9 = new javax.swing.JSpinner();
        jSpinner10 = new javax.swing.JSpinner();
        jSpinner11 = new javax.swing.JSpinner();
        jSpinner12 = new javax.swing.JSpinner();
        pauseSimulation_Button = new javax.swing.JButton();
        Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 760));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(1286, 0, 0, 0);

        placasBaseAlmacen_DELL.setEditable(false);
        placasBaseAlmacen_DELL.setBackground(new java.awt.Color(255, 255, 255));
        placasBaseAlmacen_DELL.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(placasBaseAlmacen_DELL);
        placasBaseAlmacen_DELL.setBounds(450, 270, 80, 30);

        CPUalmacen_DELL.setEditable(false);
        CPUalmacen_DELL.setBackground(new java.awt.Color(255, 255, 255));
        CPUalmacen_DELL.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(CPUalmacen_DELL);
        CPUalmacen_DELL.setBounds(450, 310, 80, 30);

        RAMalmacen_DELL.setEditable(false);
        RAMalmacen_DELL.setBackground(new java.awt.Color(255, 255, 255));
        RAMalmacen_DELL.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(RAMalmacen_DELL);
        RAMalmacen_DELL.setBounds(450, 350, 80, 30);

        AlimentacionAlmacen_DELL.setEditable(false);
        AlimentacionAlmacen_DELL.setBackground(new java.awt.Color(255, 255, 255));
        AlimentacionAlmacen_DELL.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(AlimentacionAlmacen_DELL);
        AlimentacionAlmacen_DELL.setBounds(450, 390, 80, 30);

        TGAlmacen_DELL.setEditable(false);
        TGAlmacen_DELL.setBackground(new java.awt.Color(255, 255, 255));
        TGAlmacen_DELL.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(TGAlmacen_DELL);
        TGAlmacen_DELL.setBounds(450, 430, 80, 30);

        jLabel2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("/ 25");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(540, 270, 50, 30);

        jLabel3.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("/ 20");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(540, 310, 50, 30);

        jLabel4.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("/ 55");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(540, 350, 50, 30);

        jLabel5.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("/ 35");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(540, 390, 50, 30);

        jLabel7.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Computadores Terminados");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 530, 280, 30);

        jLabel6.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Con Tarjeta Gráfica:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 610, 150, 30);

        jLabel8.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Elementos en Almacén");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(400, 230, 230, 30);

        jLabel9.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("/ 10");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(540, 430, 50, 30);

        jLabel10.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Estándar:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 570, 80, 30);

        PCwTG_DELL.setEditable(false);
        PCwTG_DELL.setBackground(new java.awt.Color(255, 255, 255));
        PCwTG_DELL.setForeground(new java.awt.Color(51, 51, 51));
        PCwTG_DELL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCwTG_DELLActionPerformed(evt);
            }
        });
        getContentPane().add(PCwTG_DELL);
        PCwTG_DELL.setBounds(180, 610, 80, 30);

        PCEstandar_DELL.setEditable(false);
        PCEstandar_DELL.setBackground(new java.awt.Color(255, 255, 255));
        PCEstandar_DELL.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(PCEstandar_DELL);
        PCEstandar_DELL.setBounds(180, 570, 80, 30);

        jLabel11.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Ingresos:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(290, 570, 80, 30);

        ingresos_DELL.setEditable(false);
        ingresos_DELL.setBackground(new java.awt.Color(255, 255, 255));
        ingresos_DELL.setForeground(new java.awt.Color(51, 51, 51));
        ingresos_DELL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresos_DELLActionPerformed(evt);
            }
        });
        getContentPane().add(ingresos_DELL);
        ingresos_DELL.setBounds(370, 570, 80, 30);

        jLabel12.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Días para Entrega:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(470, 640, 150, 30);

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(255, 255, 255));
        jTextField10.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jTextField10);
        jTextField10.setBounds(620, 640, 80, 30);

        jLabel13.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Productores");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 230, 230, 30);

        jLabel14.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("De Fuentes");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(110, 380, 140, 30);

        jLabel15.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("De placas base");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(80, 270, 120, 30);

        jLabel16.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("De Memoria R.A.M.");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(60, 350, 140, 30);

        jLabel17.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Ensambladores");
        jLabel17.setToolTipText("");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(70, 470, 120, 30);

        jLabel18.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("de Alimentación");
        jLabel18.setToolTipText("");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(70, 400, 220, 30);

        jLabel19.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("De Tarjetas Gráficas");
        jLabel19.setToolTipText("");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(40, 430, 220, 30);

        jLabel20.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("De C.P.U.");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(130, 310, 120, 30);

        jLabel21.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Trabajadores Restantes:");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(30, 170, 250, 30);

        availibleWorkers_DELL.setEditable(false);
        availibleWorkers_DELL.setBackground(new java.awt.Color(255, 255, 255));
        availibleWorkers_DELL.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(availibleWorkers_DELL);
        availibleWorkers_DELL.setBounds(290, 170, 80, 30);

        jLabel22.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("X");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(410, 310, 20, 20);

        jLabel24.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("X");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(410, 350, 20, 20);

        jLabel23.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("X");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(410, 390, 20, 20);

        jLabel25.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("X");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(410, 430, 20, 20);

        jLabel26.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("X");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(410, 470, 20, 20);

        jLabel27.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("X");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(410, 270, 20, 20);

        jLabel28.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("PROJECT MANAGER:");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(280, 20, 190, 30);

        jLabel29.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("DIRECTOR:");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(90, 20, 100, 30);

        directorState_DELL.setEditable(false);
        directorState_DELL.setBackground(new java.awt.Color(255, 255, 255));
        directorState_DELL.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(directorState_DELL);
        directorState_DELL.setBounds(70, 60, 150, 30);

        PMState_DELL.setEditable(false);
        PMState_DELL.setBackground(new java.awt.Color(255, 255, 255));
        PMState_DELL.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(PMState_DELL);
        PMState_DELL.setBounds(280, 60, 180, 30);

        PMfaultCount_DELL.setEditable(false);
        PMfaultCount_DELL.setBackground(new java.awt.Color(255, 255, 255));
        PMfaultCount_DELL.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(PMfaultCount_DELL);
        PMfaultCount_DELL.setBounds(490, 60, 80, 30);

        PMwageLoss_DELL.setEditable(false);
        PMwageLoss_DELL.setBackground(new java.awt.Color(255, 255, 255));
        PMwageLoss_DELL.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(PMwageLoss_DELL);
        PMwageLoss_DELL.setBounds(490, 100, 80, 30);

        jLabel30.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Faltas");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(500, 30, 50, 30);

        displayDashboard_Button.setBackground(new java.awt.Color(204, 204, 204));
        displayDashboard_Button.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        displayDashboard_Button.setForeground(new java.awt.Color(51, 51, 51));
        displayDashboard_Button.setText("Ver Dashboard");
        displayDashboard_Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        displayDashboard_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayDashboard_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(displayDashboard_Button);
        displayDashboard_Button.setBounds(550, 680, 130, 30);

        PCwTG_MSI.setEditable(false);
        PCwTG_MSI.setBackground(new java.awt.Color(255, 255, 255));
        PCwTG_MSI.setForeground(new java.awt.Color(51, 51, 51));
        PCwTG_MSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCwTG_MSIActionPerformed(evt);
            }
        });
        getContentPane().add(PCwTG_MSI);
        PCwTG_MSI.setBounds(820, 610, 80, 30);

        ingresos_MSI.setEditable(false);
        ingresos_MSI.setBackground(new java.awt.Color(255, 255, 255));
        ingresos_MSI.setForeground(new java.awt.Color(51, 51, 51));
        ingresos_MSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresos_MSIActionPerformed(evt);
            }
        });
        getContentPane().add(ingresos_MSI);
        ingresos_MSI.setBounds(1010, 570, 80, 30);

        jLabel31.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Ingresos:");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(930, 570, 80, 30);

        PCEstandar_MSI.setEditable(false);
        PCEstandar_MSI.setBackground(new java.awt.Color(255, 255, 255));
        PCEstandar_MSI.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(PCEstandar_MSI);
        PCEstandar_MSI.setBounds(820, 570, 80, 30);

        jLabel32.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Estándar:");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(660, 570, 80, 30);

        jLabel33.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Computadores Terminados");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(660, 530, 280, 30);

        jLabel34.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Ensambladores");
        jLabel34.setToolTipText("");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(710, 470, 120, 30);

        jLabel35.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("X");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(1050, 470, 20, 20);

        jLabel37.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("/ 10");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(1180, 430, 50, 30);

        TGalmacen_MSI.setEditable(false);
        TGalmacen_MSI.setBackground(new java.awt.Color(255, 255, 255));
        TGalmacen_MSI.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(TGalmacen_MSI);
        TGalmacen_MSI.setBounds(1090, 430, 80, 30);

        jLabel38.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("X");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(1050, 430, 20, 20);

        jLabel39.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("De Tarjetas Gráficas");
        jLabel39.setToolTipText("");
        getContentPane().add(jLabel39);
        jLabel39.setBounds(680, 430, 220, 30);

        jLabel40.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("de Alimentación");
        jLabel40.setToolTipText("");
        getContentPane().add(jLabel40);
        jLabel40.setBounds(710, 400, 220, 30);

        jLabel41.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("De Fuentes");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(750, 380, 140, 30);

        jLabel42.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("De Memoria R.A.M.");
        getContentPane().add(jLabel42);
        jLabel42.setBounds(700, 350, 140, 30);

        fuentesAlimAlmacen_MSI.setEditable(false);
        fuentesAlimAlmacen_MSI.setBackground(new java.awt.Color(255, 255, 255));
        fuentesAlimAlmacen_MSI.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(fuentesAlimAlmacen_MSI);
        fuentesAlimAlmacen_MSI.setBounds(1090, 390, 80, 30);

        jLabel43.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("X");
        getContentPane().add(jLabel43);
        jLabel43.setBounds(1050, 390, 20, 20);

        jLabel44.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("/ 55");
        getContentPane().add(jLabel44);
        jLabel44.setBounds(1180, 350, 50, 30);

        jLabel45.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("/ 35");
        getContentPane().add(jLabel45);
        jLabel45.setBounds(1180, 390, 50, 30);

        jLabel46.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("/ 20");
        getContentPane().add(jLabel46);
        jLabel46.setBounds(1180, 310, 50, 30);

        CPUAlmacen_MSI.setEditable(false);
        CPUAlmacen_MSI.setBackground(new java.awt.Color(255, 255, 255));
        CPUAlmacen_MSI.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(CPUAlmacen_MSI);
        CPUAlmacen_MSI.setBounds(1090, 310, 80, 30);

        jLabel47.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("X");
        getContentPane().add(jLabel47);
        jLabel47.setBounds(1050, 310, 20, 20);

        jLabel48.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("De C.P.U.");
        getContentPane().add(jLabel48);
        jLabel48.setBounds(770, 310, 120, 30);

        jLabel49.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("De placas base");
        getContentPane().add(jLabel49);
        jLabel49.setBounds(720, 270, 120, 30);

        jLabel50.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("X");
        getContentPane().add(jLabel50);
        jLabel50.setBounds(1050, 270, 20, 20);

        placasBaseAlmacen_MSI.setEditable(false);
        placasBaseAlmacen_MSI.setBackground(new java.awt.Color(255, 255, 255));
        placasBaseAlmacen_MSI.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(placasBaseAlmacen_MSI);
        placasBaseAlmacen_MSI.setBounds(1090, 270, 80, 30);

        jLabel51.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 0, 0));
        jLabel51.setText("/ 25");
        getContentPane().add(jLabel51);
        jLabel51.setBounds(1180, 270, 50, 30);

        jLabel52.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 0, 0));
        jLabel52.setText("Elementos en Almacén");
        getContentPane().add(jLabel52);
        jLabel52.setBounds(1040, 230, 230, 30);

        jLabel53.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(0, 0, 0));
        jLabel53.setText("Productores");
        getContentPane().add(jLabel53);
        jLabel53.setBounds(670, 230, 230, 30);

        jLabel54.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(0, 0, 0));
        jLabel54.setText("Trabajadores Restantes:");
        getContentPane().add(jLabel54);
        jLabel54.setBounds(670, 170, 250, 30);

        availibleWorkers_MSI.setEditable(false);
        availibleWorkers_MSI.setBackground(new java.awt.Color(255, 255, 255));
        availibleWorkers_MSI.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(availibleWorkers_MSI);
        availibleWorkers_MSI.setBounds(930, 170, 80, 30);

        PMwageLoss_MSI.setEditable(false);
        PMwageLoss_MSI.setBackground(new java.awt.Color(255, 255, 255));
        PMwageLoss_MSI.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(PMwageLoss_MSI);
        PMwageLoss_MSI.setBounds(1130, 100, 80, 30);

        PMFaultCount_MSI.setEditable(false);
        PMFaultCount_MSI.setBackground(new java.awt.Color(255, 255, 255));
        PMFaultCount_MSI.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(PMFaultCount_MSI);
        PMFaultCount_MSI.setBounds(1130, 60, 80, 30);

        jLabel55.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 0, 0));
        jLabel55.setText("Faltas");
        getContentPane().add(jLabel55);
        jLabel55.setBounds(1140, 30, 50, 30);

        jLabel56.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 0, 0));
        jLabel56.setText("PROJECT MANAGER:");
        getContentPane().add(jLabel56);
        jLabel56.setBounds(920, 20, 190, 30);

        PMState_MSI.setEditable(false);
        PMState_MSI.setBackground(new java.awt.Color(255, 255, 255));
        PMState_MSI.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(PMState_MSI);
        PMState_MSI.setBounds(920, 60, 180, 30);

        directorState_MSI.setEditable(false);
        directorState_MSI.setBackground(new java.awt.Color(255, 255, 255));
        directorState_MSI.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(directorState_MSI);
        directorState_MSI.setBounds(710, 60, 150, 30);

        jLabel57.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 0, 0));
        jLabel57.setText("DIRECTOR:");
        getContentPane().add(jLabel57);
        jLabel57.setBounds(730, 20, 100, 30);

        RAMalmacen_MSI.setEditable(false);
        RAMalmacen_MSI.setBackground(new java.awt.Color(255, 255, 255));
        RAMalmacen_MSI.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(RAMalmacen_MSI);
        RAMalmacen_MSI.setBounds(1090, 350, 80, 30);

        jLabel58.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 0, 0));
        jLabel58.setText("X");
        getContentPane().add(jLabel58);
        jLabel58.setBounds(1050, 350, 20, 20);

        back_Button.setBackground(new java.awt.Color(204, 204, 204));
        back_Button.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        back_Button.setForeground(new java.awt.Color(51, 51, 51));
        back_Button.setText("Regresar");
        back_Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(back_Button);
        back_Button.setBounds(20, 680, 130, 30);

        jSpinner1.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jSpinner1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSpinner1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSpinner1);
        jSpinner1.setBounds(340, 430, 60, 22);

        jSpinner2.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jSpinner2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSpinner2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSpinner2);
        jSpinner2.setBounds(340, 390, 60, 22);

        jSpinner3.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jSpinner3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSpinner3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSpinner3);
        jSpinner3.setBounds(340, 350, 60, 22);

        jSpinner4.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jSpinner4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSpinner4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSpinner4);
        jSpinner4.setBounds(340, 310, 60, 22);

        jSpinner5.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jSpinner5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSpinner5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSpinner5);
        jSpinner5.setBounds(340, 270, 60, 22);

        jSpinner6.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jSpinner6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSpinner6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSpinner6);
        jSpinner6.setBounds(340, 470, 60, 22);

        jSpinner7.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jSpinner7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSpinner7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSpinner7);
        jSpinner7.setBounds(980, 470, 60, 22);

        jSpinner8.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jSpinner8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSpinner8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSpinner8);
        jSpinner8.setBounds(980, 430, 60, 22);

        jSpinner9.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jSpinner9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSpinner9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSpinner9);
        jSpinner9.setBounds(980, 390, 60, 22);

        jSpinner10.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jSpinner10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSpinner10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSpinner10);
        jSpinner10.setBounds(980, 350, 60, 22);

        jSpinner11.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jSpinner11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSpinner11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSpinner11);
        jSpinner11.setBounds(980, 310, 60, 22);

        jSpinner12.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jSpinner12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSpinner12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSpinner12);
        jSpinner12.setBounds(980, 270, 60, 22);

        pauseSimulation_Button.setBackground(new java.awt.Color(204, 204, 204));
        pauseSimulation_Button.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        pauseSimulation_Button.setForeground(new java.awt.Color(51, 51, 51));
        pauseSimulation_Button.setText("Pausar Simulación");
        pauseSimulation_Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pauseSimulation_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseSimulation_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pauseSimulation_Button);
        pauseSimulation_Button.setBounds(1130, 680, 130, 30);

        Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Modelos - Proyecto SSOO 1.png"))); // NOI18N
        getContentPane().add(Wallpaper);
        Wallpaper.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PCwTG_DELLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCwTG_DELLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PCwTG_DELLActionPerformed

    private void ingresos_DELLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresos_DELLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresos_DELLActionPerformed

    private void displayDashboard_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayDashboard_ButtonActionPerformed
        Dashboard db = new Dashboard(puppetMasterMagenta, puppetMasterNeon);
    }//GEN-LAST:event_displayDashboard_ButtonActionPerformed

    private void PCwTG_MSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCwTG_MSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PCwTG_MSIActionPerformed

    private void ingresos_MSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresos_MSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresos_MSIActionPerformed

    private void back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_ButtonActionPerformed
        this.setVisible(false);
        Dashboard db = new Dashboard(puppetMasterMagenta, puppetMasterNeon);
    }//GEN-LAST:event_back_ButtonActionPerformed
  
    private void pauseSimulation_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseSimulation_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pauseSimulation_ButtonActionPerformed

  // +++++++++++++++++ FUNCTIONS +++++++++++++++++
    private void summonPiecesData() {
        int[] dellData = puppetMasterMagenta.sendPiecesData();
        int[] msiData = puppetMasterNeon.sendPiecesData();

        placasBaseAlmacen_DELL.setText(String.valueOf(dellData[0]));
        CPUalmacen_DELL.setText(String.valueOf(dellData[1]));
        RAMalmacen_DELL.setText(String.valueOf(dellData[2]));
        AlimentacionAlmacen_DELL.setText(String.valueOf(dellData[3]));
        TGAlmacen_DELL.setText(String.valueOf(dellData[4]));

        placasBaseAlmacen_MSI.setText(String.valueOf(msiData[0]));
        CPUAlmacen_MSI.setText(String.valueOf(msiData[1]));
        RAMalmacen_MSI.setText(String.valueOf(msiData[2]));
        fuentesAlimAlmacen_MSI.setText(String.valueOf(msiData[3]));
        TGalmacen_MSI.setText(String.valueOf(msiData[4]));
    }

    private void summonCompletePCData(){
        int[] dellData = puppetMasterMagenta.sendComputerData();
        int[] msiData = puppetMasterNeon.sendComputerData();

        PCEstandar_DELL.setText(String.valueOf(dellData[0]));
        PCwTG_DELL.setText(String.valueOf(dellData[1]));

        PCEstandar_MSI.setText(String.valueOf(msiData[0]));
        PCwTG_MSI.setText(String.valueOf(msiData[1]));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimulationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimulationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimulationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimulationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimulationScreen(puppetMasterMagenta, puppetMasterNeon).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlimentacionAlmacen_DELL;
    private javax.swing.JTextField CPUAlmacen_MSI;
    private javax.swing.JTextField CPUalmacen_DELL;
    private javax.swing.JTextField PCEstandar_DELL;
    private javax.swing.JTextField PCEstandar_MSI;
    private javax.swing.JTextField PCwTG_DELL;
    private javax.swing.JTextField PCwTG_MSI;
    private javax.swing.JTextField PMFaultCount_MSI;
    private javax.swing.JTextField PMState_DELL;
    private javax.swing.JTextField PMState_MSI;
    private javax.swing.JTextField PMfaultCount_DELL;
    private javax.swing.JTextField PMwageLoss_DELL;
    private javax.swing.JTextField PMwageLoss_MSI;
    private javax.swing.JTextField RAMalmacen_DELL;
    private javax.swing.JTextField RAMalmacen_MSI;
    private javax.swing.JTextField TGAlmacen_DELL;
    private javax.swing.JTextField TGalmacen_MSI;
    private javax.swing.JLabel Wallpaper;
    private javax.swing.JTextField availibleWorkers_DELL;
    private javax.swing.JTextField availibleWorkers_MSI;
    private javax.swing.JButton back_Button;
    private javax.swing.JTextField directorState_DELL;
    private javax.swing.JTextField directorState_MSI;
    private javax.swing.JButton displayDashboard_Button;
    private javax.swing.JTextField fuentesAlimAlmacen_MSI;
    private javax.swing.JTextField ingresos_DELL;
    private javax.swing.JTextField ingresos_MSI;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner10;
    private javax.swing.JSpinner jSpinner11;
    private javax.swing.JSpinner jSpinner12;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JSpinner jSpinner9;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JButton pauseSimulation_Button;
    private javax.swing.JTextField placasBaseAlmacen_DELL;
    private javax.swing.JTextField placasBaseAlmacen_MSI;
    // End of variables declaration//GEN-END:variables
}
